import type { IncomeRecord, IncomeDetail } from '../_types/income.types';

export const INCOME_RECORDS: IncomeRecord[] = [
  {
    id: '1',
    correlativo: 'LEF-2024-00147',
    fechaIngreso: '2024-11-04',
    solicitante: 'Q.F. María López',
    empresa: 'Laboratorios Farma S.A.',
    producto: 'Amoxicilina 500mg Cápsulas',
    tipoTramite: 'Registro Sanitario',
    estadoActual: 'FFQQ',
    areaActual: 'FFQQ',
    diasTranscurridos: 28,
    diasLimite: 45,
    sla: 'warning',
    prioridad: 'Alta',
    bloqueado: false,
    estadoGlobal: 'En Análisis FFQQ',
    responsableActual: 'Q.F. Ana Reyes',
    progreso: 62,
    pasos: [
      { area: 'RAC', abrev: 'RAC', status: 'completado', fechaInicio: '2024-11-04', fechaFin: '2024-11-06', diasUsados: 2, diasDisponibles: 5 },
      { area: 'Documentación', abrev: 'DOCT', status: 'completado', fechaInicio: '2024-11-06', fechaFin: '2024-11-14', diasUsados: 8, diasDisponibles: 10 },
      { area: 'Estándar', abrev: 'EST', status: 'completado', fechaInicio: '2024-11-14', fechaFin: '2024-11-18', diasUsados: 4, diasDisponibles: 5 },
      { area: 'FFQQ', abrev: 'FFQQ', status: 'activo', fechaInicio: '2024-11-18', diasUsados: 14, diasDisponibles: 15 },
      { area: 'Microbiología', abrev: 'MICRO', status: 'pendiente' },
      { area: 'STCC', abrev: 'STCC', status: 'pendiente' },
      { area: 'Dir. Técnica', abrev: 'DT', status: 'pendiente' },
      { area: 'Dir. General', abrev: 'DG', status: 'pendiente' },
    ],
  },
  {
    id: '2',
    correlativo: 'LEF-2024-00148',
    fechaIngreso: '2024-11-05',
    solicitante: 'Ing. Carlos Mendez',
    empresa: 'BioTech Honduras',
    producto: 'Ibuprofeno 400mg Tabletas',
    tipoTramite: 'Renovacion',
    estadoActual: 'DOCT',
    areaActual: 'Documentación',
    diasTranscurridos: 6,
    diasLimite: 30,
    sla: 'ok',
    prioridad: 'Media',
    bloqueado: false,
    responsableActual: 'Lic. Rosa Flores',
    progreso: 20,
    pasos: [
      { area: 'RAC', abrev: 'RAC', status: 'completado', fechaInicio: '2024-11-05', fechaFin: '2024-11-06', diasUsados: 1, diasDisponibles: 5 },
      { area: 'Documentación', abrev: 'DOCT', status: 'activo', fechaInicio: '2024-11-06', diasUsados: 5, diasDisponibles: 10 },
      { area: 'Estándar', abrev: 'EST', status: 'pendiente' },
      { area: 'FFQQ', abrev: 'FFQQ', status: 'pendiente' },
      { area: 'Microbiología', abrev: 'MICRO', status: 'pendiente' },
      { area: 'STCC', abrev: 'STCC', status: 'pendiente' },
      { area: 'Dir. Técnica', abrev: 'DT', status: 'pendiente' },
      { area: 'Dir. General', abrev: 'DG', status: 'pendiente' },
    ],
  },
  {
    id: '3',
    correlativo: 'LEF-2024-00143',
    fechaIngreso: '2024-10-20',
    solicitante: 'Dr. José Herrera',
    empresa: 'MedFarma S.R.L.',
    producto: 'Metformina 850mg Tabletas',
    tipoTramite: 'Modificacion',
    estadoActual: 'STCC',
    areaActual: 'STCC',
    diasTranscurridos: 42,
    diasLimite: 45,
    sla: 'danger',
    prioridad: 'Alta',
    bloqueado: true,
    motivoBloqueo: 'Pendiente de documentación adicional solicitada por STCC',
    responsableActual: 'Q.F. Pedro Alvarado',
    progreso: 85,
    pasos: [
      { area: 'RAC', abrev: 'RAC', status: 'completado', fechaInicio: '2024-10-20', fechaFin: '2024-10-22', diasUsados: 2, diasDisponibles: 5 },
      { area: 'Documentación', abrev: 'DOCT', status: 'completado', fechaInicio: '2024-10-22', fechaFin: '2024-10-30', diasUsados: 8, diasDisponibles: 10 },
      { area: 'Estándar', abrev: 'EST', status: 'completado', fechaInicio: '2024-10-30', fechaFin: '2024-11-03', diasUsados: 4, diasDisponibles: 5 },
      { area: 'FFQQ', abrev: 'FFQQ', status: 'completado', fechaInicio: '2024-11-03', fechaFin: '2024-11-12', diasUsados: 9, diasDisponibles: 15 },
      { area: 'Microbiología', abrev: 'MICRO', status: 'completado', fechaInicio: '2024-11-12', fechaFin: '2024-11-16', diasUsados: 4, diasDisponibles: 7 },
      { area: 'STCC', abrev: 'STCC', status: 'activo', fechaInicio: '2024-11-16', diasUsados: 16, diasDisponibles: 5 },
      { area: 'Dir. Técnica', abrev: 'DT', status: 'pendiente' },
      { area: 'Dir. General', abrev: 'DG', status: 'pendiente' },
    ],
  },
  {
    id: '4',
    correlativo: 'LEF-2024-00139',
    fechaIngreso: '2024-10-10',
    solicitante: 'Lic. Sandra Torres',
    empresa: 'PharmaCentral',
    producto: 'Atorvastatina 20mg Tabletas',
    tipoTramite: 'Registro Sanitario',
    estadoActual: 'FINALIZADO',
    areaActual: 'Finalizado',
    diasTranscurridos: 52,
    diasLimite: 60,
    sla: 'ok',
    prioridad: 'Media',
    bloqueado: false,
    progreso: 100,
    pasos: [
      { area: 'RAC', abrev: 'RAC', status: 'completado' },
      { area: 'Documentación', abrev: 'DOCT', status: 'completado' },
      { area: 'Estándar', abrev: 'EST', status: 'completado' },
      { area: 'FFQQ', abrev: 'FFQQ', status: 'completado' },
      { area: 'Microbiología', abrev: 'MICRO', status: 'completado' },
      { area: 'STCC', abrev: 'STCC', status: 'completado' },
      { area: 'Dir. Técnica', abrev: 'DT', status: 'completado' },
      { area: 'Dir. General', abrev: 'DG', status: 'completado' },
    ],
  },
  {
    id: '5',
    correlativo: 'LEF-2024-00152',
    fechaIngreso: '2024-11-08',
    solicitante: 'Q.F. Laura Castillo',
    empresa: 'Genéricos del Norte',
    producto: 'Omeprazol 20mg Cápsulas',
    tipoTramite: 'Renovacion',
    estadoActual: 'RAC',
    areaActual: 'RAC',
    diasTranscurridos: 2,
    diasLimite: 30,
    sla: 'ok',
    prioridad: 'Baja',
    bloqueado: false,
    responsableActual: 'Téc. Mario Ramos',
    progreso: 5,
    pasos: [
      { area: 'RAC', abrev: 'RAC', status: 'activo', fechaInicio: '2024-11-08', diasUsados: 2, diasDisponibles: 5 },
      { area: 'Documentación', abrev: 'DOCT', status: 'pendiente' },
      { area: 'Estándar', abrev: 'EST', status: 'pendiente' },
      { area: 'FFQQ', abrev: 'FFQQ', status: 'pendiente' },
      { area: 'Microbiología', abrev: 'MICRO', status: 'pendiente' },
      { area: 'STCC', abrev: 'STCC', status: 'pendiente' },
      { area: 'Dir. Técnica', abrev: 'DT', status: 'pendiente' },
      { area: 'Dir. General', abrev: 'DG', status: 'pendiente' },
    ],
  },
  {
    id: '6',
    correlativo: 'LEF-2024-00135',
    fechaIngreso: '2024-10-01',
    solicitante: 'Dr. Roberto Pineda',
    empresa: 'Laboratorio El Sol',
    producto: 'Ciprofloxacino 500mg Tabletas',
    tipoTramite: 'Reanalisis',
    estadoActual: 'DEVUELTO',
    areaActual: 'Devuelto',
    diasTranscurridos: 61,
    diasLimite: 45,
    sla: 'danger',
    prioridad: 'Alta',
    bloqueado: false,
    progreso: 40,
    pasos: [
      { area: 'RAC', abrev: 'RAC', status: 'completado' },
      { area: 'Documentación', abrev: 'DOCT', status: 'completado' },
      { area: 'Estándar', abrev: 'EST', status: 'saltado' },
      { area: 'FFQQ', abrev: 'FFQQ', status: 'completado' },
      { area: 'Microbiología', abrev: 'MICRO', status: 'pendiente' },
      { area: 'STCC', abrev: 'STCC', status: 'pendiente' },
      { area: 'Dir. Técnica', abrev: 'DT', status: 'pendiente' },
      { area: 'Dir. General', abrev: 'DG', status: 'pendiente' },
    ],
  },
  {
    id: '7',
    correlativo: 'LEF-2024-00150',
    fechaIngreso: '2024-11-07',
    solicitante: 'Lic. Patricia Zelaya',
    empresa: 'Importadora MedSalud',
    producto: 'Losartán 50mg Tabletas',
    tipoTramite: 'Registro Sanitario',
    estadoActual: 'MICRO',
    areaActual: 'Microbiología',
    diasTranscurridos: 21,
    diasLimite: 45,
    sla: 'ok',
    prioridad: 'Media',
    bloqueado: false,
    responsableActual: 'Q.F. Carmen Núñez',
    progreso: 70,
    pasos: [
      { area: 'RAC', abrev: 'RAC', status: 'completado', diasUsados: 2, diasDisponibles: 5 },
      { area: 'Documentación', abrev: 'DOCT', status: 'completado', diasUsados: 7, diasDisponibles: 10 },
      { area: 'Estándar', abrev: 'EST', status: 'completado', diasUsados: 3, diasDisponibles: 5 },
      { area: 'FFQQ', abrev: 'FFQQ', status: 'completado', diasUsados: 8, diasDisponibles: 15 },
      { area: 'Microbiología', abrev: 'MICRO', status: 'activo', fechaInicio: '2024-11-24', diasUsados: 1, diasDisponibles: 7 },
      { area: 'STCC', abrev: 'STCC', status: 'pendiente' },
      { area: 'Dir. Técnica', abrev: 'DT', status: 'pendiente' },
      { area: 'Dir. General', abrev: 'DG', status: 'pendiente' },
    ],
  },
  {
    id: '8',
    correlativo: 'LEF-2024-00141',
    fechaIngreso: '2024-10-15',
    solicitante: 'Q.F. Diana Espinal',
    empresa: 'AgroPharma S.A.',
    producto: 'Dexametasona 4mg/2ml Inyectable',
    tipoTramite: 'Homologacion',
    estadoActual: 'DT',
    areaActual: 'Dir. Técnica',
    diasTranscurridos: 47,
    diasLimite: 60,
    sla: 'ok',
    prioridad: 'Media',
    bloqueado: false,
    responsableActual: 'Dr. Luis Morales',
    progreso: 92,
    pasos: [
      { area: 'RAC', abrev: 'RAC', status: 'completado', diasUsados: 2, diasDisponibles: 5 },
      { area: 'Documentación', abrev: 'DOCT', status: 'completado', diasUsados: 9, diasDisponibles: 10 },
      { area: 'Estándar', abrev: 'EST', status: 'completado', diasUsados: 4, diasDisponibles: 5 },
      { area: 'FFQQ', abrev: 'FFQQ', status: 'completado', diasUsados: 14, diasDisponibles: 15 },
      { area: 'Microbiología', abrev: 'MICRO', status: 'completado', diasUsados: 6, diasDisponibles: 7 },
      { area: 'STCC', abrev: 'STCC', status: 'completado', diasUsados: 5, diasDisponibles: 5 },
      { area: 'Dir. Técnica', abrev: 'DT', status: 'activo', fechaInicio: '2024-11-27', diasUsados: 7, diasDisponibles: 10 },
      { area: 'Dir. General', abrev: 'DG', status: 'pendiente' },
    ],
  },
  {
    id: '9',
    correlativo: 'LEF-2024-00153',
    fechaIngreso: '2024-11-09',
    solicitante: 'Ing. Marcos Soto',
    empresa: 'NovaMed Honduras',
    producto: 'Paracetamol 500mg Tabletas',
    tipoTramite: 'Renovacion',
    estadoActual: 'ESTANDAR',
    areaActual: 'Estándar',
    diasTranscurridos: 9,
    diasLimite: 30,
    sla: 'ok',
    prioridad: 'Baja',
    bloqueado: false,
    responsableActual: 'Téc. Gloria Mejía',
    progreso: 30,
    pasos: [
      { area: 'RAC', abrev: 'RAC', status: 'completado', diasUsados: 2, diasDisponibles: 5 },
      { area: 'Documentación', abrev: 'DOCT', status: 'completado', diasUsados: 5, diasDisponibles: 10 },
      { area: 'Estándar', abrev: 'EST', status: 'activo', fechaInicio: '2024-11-15', diasUsados: 2, diasDisponibles: 5 },
      { area: 'FFQQ', abrev: 'FFQQ', status: 'pendiente' },
      { area: 'Microbiología', abrev: 'MICRO', status: 'pendiente' },
      { area: 'STCC', abrev: 'STCC', status: 'pendiente' },
      { area: 'Dir. Técnica', abrev: 'DT', status: 'pendiente' },
      { area: 'Dir. General', abrev: 'DG', status: 'pendiente' },
    ],
  },
  {
    id: '10',
    correlativo: 'LEF-2024-00144',
    fechaIngreso: '2024-10-22',
    solicitante: 'Q.F. Isabel Reyes',
    empresa: 'Distribuidora Salud Total',
    producto: 'Furosemida 40mg Tabletas',
    tipoTramite: 'Modificacion',
    estadoActual: 'DG',
    areaActual: 'Dir. General',
    diasTranscurridos: 41,
    diasLimite: 45,
    sla: 'warning',
    prioridad: 'Alta',
    bloqueado: false,
    responsableActual: 'Dir. General',
    progreso: 97,
    pasos: [
      { area: 'RAC', abrev: 'RAC', status: 'completado', diasUsados: 2, diasDisponibles: 5 },
      { area: 'Documentación', abrev: 'DOCT', status: 'completado', diasUsados: 8, diasDisponibles: 10 },
      { area: 'Estándar', abrev: 'EST', status: 'completado', diasUsados: 4, diasDisponibles: 5 },
      { area: 'FFQQ', abrev: 'FFQQ', status: 'completado', diasUsados: 13, diasDisponibles: 15 },
      { area: 'Microbiología', abrev: 'MICRO', status: 'completado', diasUsados: 6, diasDisponibles: 7 },
      { area: 'STCC', abrev: 'STCC', status: 'completado', diasUsados: 4, diasDisponibles: 5 },
      { area: 'Dir. Técnica', abrev: 'DT', status: 'completado', diasUsados: 3, diasDisponibles: 10 },
      { area: 'Dir. General', abrev: 'DG', status: 'activo', fechaInicio: '2024-12-01', diasUsados: 1, diasDisponibles: 5 },
    ],
  },
];

// ─── Full detail for LEF-2024-00147 ─────────────────────────────────────────
export const INCOME_DETAIL_00147: IncomeDetail = {
  ...INCOME_RECORDS[0],
  solicitanteDetalle: {
    nombre: 'Q.F. María López',
    empresa: 'Laboratorios Farma S.A.',
    telefono: '+504 9876-5432',
    email: 'mlopez@farma.hn',
    nit: '0801-1990-12345',
  },
  productoDetalle: {
    nombreComercial: 'AMOXIFAR 500',
    nombreGenerico: 'Amoxicilina',
    fabricante: 'Laboratorios Farma S.A.',
    paisOrigen: 'Honduras',
    formaFarmaceutica: 'Cápsulas',
    concentracion: '500 mg',
    presentacion: 'Caja x 20 cápsulas',
    condicionVenta: 'Bajo receta médica',
    lote: 'A-2024-087',
    cantidadMuestra: 60,
  },
  rac: {
    fechaIngreso: '2024-11-04',
    horaIngreso: '09:15',
    receptor: 'Téc. Mario Ramos',
    proforma: 'PRF-2024-0892',
    montoPagado: 3500,
    fechaPago: '2024-11-04',
    distribucionRt159: true,
    observaciones: 'Muestra recibida en condiciones óptimas. Documentación completa.',
    // RG-41
    nroRecepcion: 'REC-2024-00147',
    mesRecepcion: 'Noviembre 2024',
    tipoTramiteRac: 'Registro Sanitario',
    prioridadRac: 'ALTA',
    // Referencias
    nroOrden: 'ORD-FARMA-2024-0089',
    nroExpediente: 'EXP-0147-2024',
    nroLicitacion: 'N/A',
    nroCarta: 'FARMA-2024-0234',
    // Cantidades
    cantidadesPorDestino: [
      { destino: 'Total Recibida RAC', cantidad: 60,  unidad: 'cápsulas' },
      { destino: 'FFQQ (Análisis)',    cantidad: 20,  unidad: 'cápsulas' },
      { destino: 'Microbiología',      cantidad: 20,  unidad: 'cápsulas' },
      { destino: 'Muestra Biblioteca', cantidad: 20,  unidad: 'cápsulas' },
    ],
    // Verificación documental
    verificacionDocumental: [
      { descripcion: 'Solicitud de registro firmada',         cumple: true,  requerido: true  },
      { descripcion: 'Proforma cancelada',                   cumple: true,  requerido: true  },
      { descripcion: 'Certificado de libre venta',           cumple: true,  requerido: true  },
      { descripcion: 'Registro sanitario vigente',           cumple: true,  requerido: true  },
      { descripcion: 'Certificado de análisis del fabricante',cumple: true, requerido: false },
      { descripcion: 'Metodología analítica validada',       cumple: false, requerido: false },
      { descripcion: 'Especificaciones del producto',        cumple: true,  requerido: false },
    ],
    // RT-159 detalle
    distribucionDetalle: [
      { area: 'RAC',           accion: 'Emisión',   fecha: '2024-11-04', responsable: 'Téc. Mario Ramos',  estado: 'completado' },
      { area: 'DOCT',          accion: 'Recibido',  fecha: '2024-11-06', responsable: 'Lic. Rosa Flores',  estado: 'completado' },
      { area: 'Microbiología', accion: 'Recibido',  fecha: '2024-11-18', responsable: 'Q.F. Carmen Núñez', estado: 'completado' },
    ],
    checklist: [
      { id: 'c1', descripcion: 'Solicitud de registro firmada', completado: true, obligatorio: true, area: 'RAC' },
      { id: 'c2', descripcion: 'Proforma cancelada', completado: true, obligatorio: true, area: 'RAC' },
      { id: 'c3', descripcion: 'Muestras recibidas (mínimo 60 unidades)', completado: true, obligatorio: true, area: 'RAC' },
      { id: 'c4', descripcion: 'Formulario RT-159 completado', completado: true, obligatorio: true, area: 'RAC' },
      { id: 'c5', descripcion: 'Cédula del solicitante', completado: true, obligatorio: false, area: 'RAC' },
    ],
  },
  doct: {
    tecnico: 'Lic. Rosa Flores',
    fechaRevision: '2024-11-14',
    rt75Estado: 'completado',
    rt41Estado: 'completado',
    rt30Estado: 'pendiente',
    rt38Estado: 'completado',
    observaciones: 'Documentación técnica revisada y aprobada. Expediente completo.',
    // RT-75
    rt75Solicitante: 'Lic. Rosa Flores',
    rt75FechaSolicitud: '2024-11-06',
    rt75FechaRespuesta: '2024-11-08',
    rt75RecepcionesPrevias: 3,
    // RT-41
    rt41Filas: [
      { recepcion: 'LEF-2022-00098', fecha: '2022-03-15', lote: 'AM2209A', tramite: 'Registro Sanitario', resultado: 'Conforme',     analista: 'Q.F. Ana Reyes', observaciones: 'Sin observaciones. Todas las pruebas dentro de especificación.' },
      { recepcion: 'LEF-2023-00112', fecha: '2023-04-20', lote: 'AM2302B', tramite: 'Renovacion',         resultado: 'No Conforme',  analista: 'Q.F. Ana Reyes', observaciones: 'Prueba de disolución fuera de especificación en 2 unidades.' },
      { recepcion: 'LEF-2023-00089', fecha: '2023-09-10', lote: 'AM2309A', tramite: 'Registro Sanitario', resultado: 'Conforme',     analista: 'Q.F. Ana Reyes', observaciones: 'Conforme. Estándar de referencia utilizado: USP RS.' },
    ],
    // RT-38
    rt38EstadoGlobal: 'En Captura FFQQ',
    rt38CreadoPor: 'Ana Patricia Flores',
    rt38FechaCreacion: '2024-11-16',
    rt38PruebasConfiguradas: 8,
    rt38FechaPruebas: '2024-11-16',
    rt38AuxiliaresGenerados: 4,
    rt38FechaAuxiliares: '2024-11-16',
    rt38PaqueteEnviadoA: 'Q.F. Ana Reyes',
    rt38FechaPaquete: '2024-11-18',
    // RT-30
    rt30FechaEmision: '2024-11-08',
    rt30FirmadoPor: 'Lic. Rosa Flores — DOCT',
    rt30EnviadoA: 'Téc. Gloria Mejía — Estándar',
    rt30PlazoLimite: '2025-01-08',
    rt30DiasTranscurridos: 7,
    rt30DiasTotal: 60,
    rt30Items: [
      { descripcion: 'Estándar de referencia: Amoxicilina Trihidrato USP RS', estado: 'completado' },
      { descripcion: 'Metodología analítica actualizada (HPLC)',               estado: 'pendiente'  },
      { descripcion: 'Certificado de análisis del lote A-2024-087',            estado: 'completado' },
    ],
    checklist: [
      { id: 'd1', descripcion: 'Certificado de libre venta', completado: true, obligatorio: true, area: 'DOCT' },
      { id: 'd2', descripcion: 'Fórmula cuali-cuantitativa', completado: true, obligatorio: true, area: 'DOCT' },
      { id: 'd3', descripcion: 'Método de análisis validado', completado: true, obligatorio: true, area: 'DOCT' },
      { id: 'd4', descripcion: 'Estabilidad del producto', completado: true, obligatorio: true, area: 'DOCT' },
      { id: 'd5', descripcion: 'Etiqueta y empaque', completado: true, obligatorio: true, area: 'DOCT' },
      { id: 'd6', descripcion: 'Buenas Prácticas de Manufactura', completado: true, obligatorio: false, area: 'DOCT' },
    ],
  },
  estandar: {
    codigo: 'EST-2024-0892',
    estado: 'entregado',
    analista: 'Téc. Gloria Mejía',
    fechaRegistro: '2024-11-18',
    rg44Estado: 'completado',
    rt27Estado: 'completado',
    observaciones: 'Estándar preparado y entregado correctamente al área FFQQ.',
    // RG-44 detalle
    registroInterno: 'RG44-2024-0892',
    nombreEstandar: 'Amoxicilina Trihidrato USP RS',
    loteCodigo: 'STD-AMX-2024-001',
    nroCertificado: 'USP-RS-AMX-2024',
    cantidadTotal: 200,
    cantidadDisponible: 150,
    cantidadUsada: 50,
    unidadMedida: 'mg',
    condicionesAlmacenamiento: '2–8°C, protegido de la luz',
    fechaRecepcion: '2024-11-14',
    fechaAceptacion: '2024-11-14',
    fechaVencimiento: '31/12/2024',
    validadoPor: 'Téc. Gloria Mejía',
    entregaRt27: 'RT-27-2024-0892',
    alertaVencimiento: true,
    movimientos: [
      { codigo: 'RG-44', descripcion: 'Registro inicial', responsable: 'Téc. Gloria Mejía', fecha: '2024-11-14', cantidad: 200, unidad: 'mg' },
      { codigo: 'RT-27', descripcion: 'Entrega a FFQQ',  responsable: 'Téc. Gloria Mejía', fecha: '2024-11-18', cantidad: -50, unidad: 'mg' },
    ],
  },
  ffqq: {
    analistas: ['Karla Suazo', 'Jorge Matute'],
    rt40Emitido: '18/01/2024',
    str: 'Roberto Paz',
    analista: 'Karla Suazo',
    fechaInicio: '2024-11-18',
    pruebas: [
      { id: 'f1', codigo: 'P-01', prueba: 'Descripción / Aspecto',     tecnica: 'Visual',               analista: 'Karla', estado: 'completada', cumple: true,  fecha: '2024-11-20', especificacion: 'Cápsulas de gelatina dura, color amarillo, uniformes',                        resultado: 'Cápsulas de gelatina dura, de color amarillo opaco, sin manchas ni deformaciones.' },
      { id: 'f2', codigo: 'P-02', prueba: 'Identificación (IR)',         tecnica: 'Espectroscopía IR',    analista: 'Karla', estado: 'completada', cumple: true,  fecha: '2024-11-20', especificacion: 'Espectro IR concordante con estándar de referencia',                          resultado: 'Espectro IR concordante. Bandas características confirmadas a 1689 y 1530 cm⁻¹.' },
      { id: 'f3', codigo: 'P-03', prueba: 'Valoración (HPLC)',           tecnica: 'HPLC',                 analista: 'Karla', estado: 'en_proceso', cumple: null, rt: 'RT-84', especificacion: '90.0% – 110.0% de la potencia declarada', resultadoObtenido: '' },
      { id: 'f4', codigo: 'P-04', prueba: 'Disolución',                  tecnica: 'Aparato II (Paletas)', analista: 'Jorge', estado: 'en_proceso', cumple: null, rt: 'RT-85', especificacion: '≥ 80% disuelto en 30 minutos (Q)' },
      { id: 'f5', codigo: 'P-05', prueba: 'Uniformidad de Peso',         tecnica: 'Gravimetría',          analista: 'Jorge', estado: 'completada', cumple: true,  fecha: '2024-11-21', especificacion: 'NMT 7.5% de variación respecto al peso promedio',                             resultado: 'Peso promedio: 312.4 mg. Variación máxima: 3.2%. Cumple especificación.' },
      { id: 'f6', codigo: 'P-06', prueba: 'Tiempo de Desintegración',    tecnica: 'Desintegración USP',   analista: 'Karla', estado: 'completada', cumple: true,  fecha: '2024-11-21', especificacion: 'NMT 15 minutos en agua a 37°C ± 2°C',                                        resultado: 'Tiempo de desintegración: 8 minutos 42 segundos. Cumple especificación.' },
      { id: 'f7', codigo: 'P-07', prueba: 'pH (Solución 1%)',            tecnica: 'Potenciometría',       analista: 'Karla', estado: 'pendiente',  cumple: null,  especificacion: '4.5 – 6.5' },
      { id: 'f8', codigo: 'P-08', prueba: 'Impurezas Relacionadas',      tecnica: 'HPLC',                 analista: 'Jorge', estado: 'pendiente',  cumple: null, rt: 'RT-86', especificacion: 'Impureza individual NMT 0.2%; Total NMT 1.0%' },
    ],
    observaciones: 'Pruebas en progreso. Se proyecta finalizar en 3 días hábiles.',
  },
  micro: {
    recepcion: {
      fechaHora: '09/01/2024 09:15',
      responsable: 'Q.F. Teresa Montoya',
      cantidad: '60 unidades',
      estadoMuestra: 'Integra, embalaje original',
    },
    aceptabilidad: {
      aceptada: true,
      texto: 'Sin evidencia de contaminación cruzada. Embalaje íntegro. Temperatura de transporte verificada.',
      fecha: '09/01/2024',
    },
    rt74Estado: 'en_proceso',
    analista: 'Q.F. Teresa Montoya',
    fechaInicio: '09/01/2024',
    pruebas: [
      { id: 'm1', prueba: 'Recuento Total de Aerobios (RTMA)',    metodo: 'USP <61>', especificacion: 'NMT 1000 UFC/g', estado: 'en_proceso', cumple: null },
      { id: 'm2', prueba: 'Recuento Total de Hongos y Levaduras', metodo: 'USP <61>', especificacion: 'NMT 100 UFC/g',  estado: 'en_proceso', cumple: null },
      { id: 'm3', prueba: 'Ausencia de Escherichia coli',         metodo: 'USP <62>', especificacion: 'Ausencia en 1g', estado: 'pendiente',  cumple: null },
      { id: 'm4', prueba: 'Ausencia de Salmonella spp.',          metodo: 'USP <62>', especificacion: 'Ausencia en 10g',estado: 'pendiente',  cumple: null },
      { id: 'm5', prueba: 'Ausencia de Staphylococcus aureus',    metodo: 'USP <62>', especificacion: 'Ausencia en 1g', estado: 'pendiente',  cumple: null },
    ],
    observaciones: 'Análisis en curso. Incubación en progreso para recuentos aerobios.',
  },
  stccDtDg: {
    stccEstado: 'en_analisis',
    stccChecklist: [
      { id: 'c1', label: 'RT-38 completo y firmado por analista',    checked: false },
      { id: 'c2', label: 'Todos los auxiliares completados',          checked: false },
      { id: 'c3', label: 'Anexos y soportes adjuntos por prueba',     checked: false },
      { id: 'c4', label: 'RT-74 completo y firmado por Micro',        checked: false },
      { id: 'c5', label: 'Resultados dentro de especificaciones',     checked: false },
      { id: 'c6', label: 'Sin inconsistencias documentales',          checked: false },
    ],
    dtEstado: 'pendiente_stcc',
    dgEstado: 'pendiente_dt',
  },
  documentos: [
    { id: 'doc1', codigo: 'RT-75', nombre: 'Revisión de Documentos Técnicos', area: 'DOCT', estado: 'completado', fechaCompletado: '2024-11-14', responsable: 'Lic. Rosa Flores' },
    { id: 'doc2', codigo: 'RT-41', nombre: 'Contraste de Documentos', area: 'DOCT', estado: 'completado', fechaCompletado: '2024-11-12', responsable: 'Lic. Rosa Flores' },
    { id: 'doc3', codigo: 'RT-38', nombre: 'Preparación de Expediente', area: 'DOCT', estado: 'completado', fechaCompletado: '2024-11-13', responsable: 'Lic. Rosa Flores' },
    { id: 'doc4', codigo: 'RT-159', nombre: 'Distribución de Muestras', area: 'RAC', estado: 'completado', fechaCompletado: '2024-11-04', responsable: 'Téc. Mario Ramos' },
    { id: 'doc5', codigo: 'RG-44', nombre: 'Registro de Estándar', area: 'Estándar', estado: 'completado', fechaCompletado: '2024-11-18', responsable: 'Téc. Gloria Mejía' },
    { id: 'doc6', codigo: 'RT-27', nombre: 'Entrega de Estándar', area: 'Estándar', estado: 'completado', fechaCompletado: '2024-11-18', responsable: 'Téc. Gloria Mejía' },
    { id: 'doc7', codigo: 'RT-88', nombre: 'Resultados FFQQ', area: 'FFQQ', estado: 'pendiente', responsable: 'Q.F. Ana Reyes' },
    { id: 'doc8', codigo: 'RT-92', nombre: 'Resultados Microbiología', area: 'Microbiología', estado: 'pendiente' },
    { id: 'doc9', codigo: 'RT-200', nombre: 'Resolución Dirección Técnica', area: 'Dir. Técnica', estado: 'pendiente' },
  ],
  timeline: [
    { id: 't1',  fecha: '07/01/2024', hora: '08:14', area: 'RAC',          usuario: 'María Rodríguez',    accion: 'Ingreso creado en borrador',                          tipo: 'ingreso' },
    { id: 't2',  fecha: '07/01/2024', hora: '09:47', area: 'RAC',          usuario: 'María Rodríguez',    accion: 'Documentación mínima verificada',                     tipo: 'documento' },
    { id: 't3',  fecha: '07/01/2024', hora: '10:05', area: 'RAC',          usuario: 'María Rodríguez',    accion: 'Registrado en RG-41 — Nº Recepción asignado',         tipo: 'documento', detalle: 'Correlativo LEF-2024-00147 generado automáticamente' },
    { id: 't4',  fecha: '07/01/2024', hora: '10:22', area: 'RAC',          usuario: 'María Rodríguez',    accion: 'RG-13 y RG-72 generados',                             tipo: 'documento' },
    { id: 't5',  fecha: '08/01/2024', hora: '14:30', area: 'Contabilidad', usuario: 'Carlos Mejía',       accion: 'Pago confirmado — Proforma P-2024-0089',              tipo: 'aprobacion' },
    { id: 't6',  fecha: '08/01/2024', hora: '15:10', area: 'RAC',          usuario: 'María Rodríguez',    accion: 'RT-159 emitido — Distribución a DOCT y Micro',        tipo: 'documento' },
    { id: 't7',  fecha: '09/01/2024', hora: '08:35', area: 'DOCT',         usuario: 'Ana Patricia Flores',accion: 'Recibido por Documentación',                          tipo: 'ingreso' },
    { id: 't8',  fecha: '09/01/2024', hora: '09:15', area: 'Micro',        usuario: 'Q.F. Teresa Montoya',accion: 'Muestra recibida en Microbiología',                   tipo: 'ingreso', detalle: 'Integra, embalaje original. 60 unidades.' },
    { id: 't9',  fecha: '09/01/2024', hora: '10:05', area: 'DOCT',         usuario: 'Ana Patricia Flores',accion: 'Inicio revisión RT-75',                               tipo: 'documento' },
    { id: 't10', fecha: '12/01/2024', hora: '16:00', area: 'DOCT',         usuario: 'Ana Patricia Flores',accion: 'Contraste RT-41 completado',                          tipo: 'documento' },
    { id: 't11', fecha: '14/01/2024', hora: '10:00', area: 'DOCT',         usuario: 'Ana Patricia Flores',accion: 'RT-38 base generado',                                 tipo: 'documento' },
    { id: 't12', fecha: '15/01/2024', hora: '11:20', area: 'DOCT',         usuario: 'Ana Patricia Flores',accion: 'Transición a STR para revisión',                      tipo: 'transicion' },
    { id: 't13', fecha: '17/01/2024', hora: '11:30', area: 'DOCT',         usuario: 'Ana Patricia Flores',accion: 'Paquete enviado a STR para revisión',                 tipo: 'aprobacion', detalle: 'RT-38 base verificado y completo.' },
    { id: 't14', fecha: '18/01/2024', hora: '09:00', area: 'STR',          usuario: 'Roberto Paz',        accion: 'Paquete aprobado — RT-40 emitido',                    tipo: 'aprobacion', detalle: 'Analistas asignados: Karla Suazo (principal) y Jorge Matute.' },
    { id: 't15', fecha: '18/01/2024', hora: '08:12', area: 'STCC',         usuario: 'Dra. Elena Valenzuela',accion: 'Observación técnica sobre RT-84',                   tipo: 'observacion', detalle: 'Auxiliar RT-84 (HPLC) requiere actualización.' },
    { id: 't16', fecha: '18/01/2024', hora: '09:30', area: 'FFQQ',         usuario: 'Karla Suazo',        accion: 'Inicio análisis fisicoquímicos RT-38',                tipo: 'ingreso' },
    { id: 't17', fecha: '20/01/2024', hora: '11:00', area: 'FFQQ',         usuario: 'Karla Suazo',        accion: 'Descripción / Aspecto — Completada',                  tipo: 'documento' },
    { id: 't18', fecha: '20/01/2024', hora: '14:00', area: 'FFQQ',         usuario: 'Jorge Matute',       accion: 'Identificación (IR) — Completada',                    tipo: 'documento' },
  ],
  observaciones: [
    { id: 'o1', fecha: '18/01/2024', hora: '08:12', area: 'STCC', ruta: 'STCC→FFQQ', usuario: 'Dra. Elena Valenzuela', texto: 'Auxiliar RT-84 (HPLC) requiere actualización. Falta columna de % de recuperación del sistema.', tipo: 'obs', visible: true },
    { id: 'o2', fecha: '17/01/2024', hora: '11:30', area: 'DOCT', ruta: 'DOCT→STR',  usuario: 'Ana Patricia Flores',   texto: 'Paquete técnico verificado y completo. RT-38 base enviado a STR para revisión.', tipo: 'aprobacion', visible: true },
    { id: 'o3', fecha: '18/01/2024', hora: '09:00', area: 'STR',  ruta: 'STR→FFQQ',  usuario: 'Roberto Paz',           texto: 'Paquete documental aprobado. RT-40 emitido. Analistas asignados: Karla Suazo (principal) y Jorge Matute.', tipo: 'aprobacion', visible: true },
    { id: 'o4', fecha: '07/01/2024', hora: '10:05', area: 'RAC',  ruta: 'RAC→DOCT',  usuario: 'María Rodríguez',       texto: 'Muestra recibida en buen estado. Embalaje original intacto. Acta de toma de muestra SESAL adjunta.', tipo: 'obs', visible: true },
  ],
  historico: [
    { correlativo: 'REC-2023-0201', tipo: 'Renovacion',         fechaIngreso: '15/09/2023', estado: 'FINALIZADO', lote: 'AM2309A', resultado: 'conforme' },
    { correlativo: 'REC-2023-0034', tipo: 'Registro Sanitario', fechaIngreso: '12/02/2023', estado: 'FINALIZADO', lote: 'AM2302B', resultado: 'no_conforme' },
    { correlativo: 'REC-2022-0089', tipo: 'Renovacion',         fechaIngreso: '28/04/2022', estado: 'FINALIZADO', lote: 'AM2204C', resultado: 'conforme' },
  ],
};

export function getIncomeDetail(correlativo: string): IncomeDetail | null {
  if (correlativo === 'LEF-2024-00147') return INCOME_DETAIL_00147;
  const record = INCOME_RECORDS.find(r => r.correlativo === correlativo);
  if (!record) return null;
  return {
    ...record,
    solicitanteDetalle: { nombre: record.solicitante, empresa: record.empresa, telefono: '', email: '', nit: '' },
    productoDetalle: { nombreComercial: record.producto, nombreGenerico: '', fabricante: record.empresa, paisOrigen: 'Honduras', formaFarmaceutica: '', concentracion: '', presentacion: '', condicionVenta: '' },
    rac: { fechaIngreso: record.fechaIngreso, horaIngreso: '08:00', receptor: '', distribucionRt159: false, checklist: [], observaciones: '' },
    doct: { tecnico: '', rt75Estado: 'pendiente', rt41Estado: 'pendiente', rt30Estado: 'pendiente', rt38Estado: 'pendiente', checklist: [] },
    estandar: { estado: 'pendiente', rg44Estado: 'pendiente', rt27Estado: 'pendiente' },
    ffqq: { pruebas: [] },
    micro: { pruebas: [] },
    stccDtDg: { stccEstado: 'pendiente', dtEstado: 'pendiente', dgEstado: 'pendiente' },
    documentos: [],
    timeline: [],
    observaciones: [],
    historico: [],
  };
}
